name: CI/CD

on:
  push:
    branches:
      - main
      - '*'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore src/Plpext/Plpext.sln

    - name: Install tools
      run: dotnet tool install --global vpk

    - name: Build Core.Windows
      run: dotnet build src/Plpext.Core.Windows/Plpext.Core.Windows.csproj --configuration Release --no-restore

    - name: Build UI
      run: dotnet build src/Plpext/Plpext.UI/Plpext.UI.csproj --configuration Release --no-restore

    - name: Dotnet publish
      run: dotnet publish src/Plpext/Plpext.UI/Plpext.UI.csproj -c Release -r win-x64 -o publish

    - name: Vpk pack
      run: vpk pack --mainExe=Plpext.exe --packId=Plpext --packVersion=1.0.${{ github.run_number }} --packDir=publish -o build/win
    
    - name: Upload artifact
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Release v1.0.${{ github.run_number }}
        files: build/win/Plpext-win-Setup.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}